# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-ci

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    ls -R $(System.DefaultWorkingDirectory)/tests/Capo.UI.Testing
  displayName: 'List Files and Directories'

- script: |
    npm install
    npx playwright install
    S3_ENDPOINT=$(S3_ENDPOINT) S3_ACCESS_KEY_ID=$(S3_ACCESS_KEY_ID) S3_SECRET_ACCESS_KEY=$(S3_SECRET_ACCESS_KEY) S3_BUCKET=$(S3_BUCKET) S3_REGION=$(S3_REGION) TESTOMATIO_PRIVATE_ARTIFACTS=1 TESTOMATIO=$(testomatio) TESTOMATIO_URL=$(testomatio_url) TESTOMATIO_RUN=$(run) CI=1 npx playwright test --grep="$(grep)" --shard=2/3
  displayName: 'npm install & run tests'
  workingDirectory: $(System.DefaultWorkingDirectory)/tests/Capo.UI.Testing

- publish: $(System.DefaultWorkingDirectory)/tests/Capo.UI.Testing/playwright/test-results
  artifact: playwright-report-$(testomatio)
  # always create the artifact, this is useful for debugging failed tests
  condition: always()
